# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryanky's universe
description: 浩淼宇宙，为何我们在此相遇
baseurl: '' # the subpath of your site, e.g. /blog
url:http://ryankies.github.io
# google_analytics: 'UA-XXXXXX-X'
Wechat_username: Ryanky

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
